    name = "backend"
main = "src/index.ts"
type = "module"
compatibility_date = "2025-08-30"
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19uTkFvLVZ6QjFzV1A1SEs1SnFFUGUiLCJhcGlfa2V5IjoiMDFLM1dBQ0FQSFZBMFZFMlZSWEpBOUNRRVMiLCJ0ZW5hbnRfaWQiOiJjN2UxY2ZjMDdkYmExNjgzYzNlMWZiYmVlZjBlZjJlMWJlMmVkM2Y2NTM4Yzk4YjVhOTZjZmM3Yjc5NmY5ODlkIiwiaW50ZXJuYWxfc2VjcmV0IjoiZmM4NTdjNDktOGM2OC00NTFmLThiMWEtYzY4NDBjZDAwNDA2In0.3h9RVXrda4oqfe01d_sLAHbur7kurSWWCCCHqrHYHTA"
JWT_SECRET ="eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19uTkFvLVZ6QjFzV1A1SEs1SnFFUGUiLCJhcGlfa2V5IjoiMDFLM1dBQ0FQSFZBMFZFMlZSWEpBOUNRRVMiLCJ0ZW5hbnRfaWQiOiJjN2UxY2ZjMDdkYmExNjgzYzNlMWZiYmVlZjBlZjJlMWJlMmVkM2Y2NTM4Yzk4YjVhOTZjZmM3Yjc5NmY5ODlkIiwiaW50ZXJuYWxfc2VjcmV0IjoiZmM4NTdjNDktOGM2OC00NTFmLThiMWEtYzY4NDBjZDAwNDA2In0"

[build]
command = "npx prisma generate"
